/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TailoringRouteImport } from './routes/tailoring'
import { Route as SuitsRouteImport } from './routes/suits'
import { Route as SareesRouteImport } from './routes/sarees'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TailoringRoute = TailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitsRoute = SuitsRouteImport.update({
  id: '/suits',
  path: '/suits',
  getParentRoute: () => rootRouteImport,
} as any)
const SareesRoute = SareesRouteImport.update({
  id: '/sarees',
  path: '/sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sarees': typeof SareesRoute
  '/suits': typeof SuitsRoute
  '/tailoring': typeof TailoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sarees': typeof SareesRoute
  '/suits': typeof SuitsRoute
  '/tailoring': typeof TailoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sarees': typeof SareesRoute
  '/suits': typeof SuitsRoute
  '/tailoring': typeof TailoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/sarees' | '/suits' | '/tailoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/sarees' | '/suits' | '/tailoring'
  id: '__root__' | '/' | '/contact' | '/sarees' | '/suits' | '/tailoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  SareesRoute: typeof SareesRoute
  SuitsRoute: typeof SuitsRoute
  TailoringRoute: typeof TailoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tailoring': {
      id: '/tailoring'
      path: '/tailoring'
      fullPath: '/tailoring'
      preLoaderRoute: typeof TailoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suits': {
      id: '/suits'
      path: '/suits'
      fullPath: '/suits'
      preLoaderRoute: typeof SuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarees': {
      id: '/sarees'
      path: '/sarees'
      fullPath: '/sarees'
      preLoaderRoute: typeof SareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  SareesRoute: SareesRoute,
  SuitsRoute: SuitsRoute,
  TailoringRoute: TailoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
